### ISSUE TITLE
ClientSession.ws_connect() got an unexpected keyword argument 'ping_interval'

### ISSUE THREAD

**Issue by shuangleo** [InterestingDarkness/ChatSydney#10]
谢谢你的代码，这一版更新后每次都报错，不知道什么原因。
Mac mini Apple M1 macOS 13.3.1 Python 3.11.3和3.10两个环节都试过，终端中都有提示“Go to http://localhost:65432 to start chatting!”，浏览器打开页面正常，但提问后就返回“ClientSession.ws_connect() got an unexpected keyword argument 'ping_interval'”错误。请教如何解决？谢谢🙏

**Comment by InterestingDarkness** [comment]
EdgeGPT 0.4.3 is broken, I've freezed EdgeGPT version https://github.com/InterestingDarkness/ChatSydney/commit/c2c87069701027f3b7342ccf0dd4fae46b647b76
