### ISSUE TITLE
Chatbot.create() got an unexpected keyword argument 'cookie_path'

### ISSUE THREAD

**Issue by yshzx545** [InterestingDarkness/ChatSydney#16]
https://github.com/InterestingDarkness/ChatSydney/blob/f2b0df522add8055a64b218bfae321999073cd0d/main.py#LL13C67-L13C67

我今天早上下载了最新代码启动之后发送消息报错

**Comment by yshzx545** [comment]
![image](https://github.com/InterestingDarkness/ChatSydney/assets/83584843/44e666ef-5842-496b-a328-15a9f06021d3)

**Comment by InterestingDarkness** [comment]
solved by freezing EdgeGPT version.

**Comment by yshzx545** [comment]
看到您已经在requirements.txt中指定版本了，此问题关闭
