### ISSUE TITLE
add cookie input on the web

### ISSUE THREAD

**Issue by renqabs** [InterestingDarkness/ChatSydney#24]
Can you add an input box to fill in cookies on the web interface, only use the _U parameters in the cookie JSON string, in the main.py to pass the cookie: cookies=[{'name':'_U','value':user_cookie_of_U}]

**Comment by InterestingDarkness** [comment]
OK https://github.com/InterestingDarkness/ChatSydney/commit/46085f9ddef135459e33f4130bc2c83936607855

**Comment by renqabs** [comment]
> OK [46085f9](https://github.com/InterestingDarkness/ChatSydney/commit/46085f9ddef135459e33f4130bc2c83936607855)

Thank you very much
