### ISSUE TITLE
add a Preset feature

### ISSUE THREAD

**Issue by renqabs** [InterestingDarkness/ChatSydney#26]
Can you add a Preset feature similar to the SydneyQt project?

**Comment by InterestingDarkness** [comment]
I think Save/Load is enough. Users may clear localStorage by mistake. So anything that relies on localStorage is unreliable.

**Comment by renqabs** [comment]
> I think Save/Load is enough. Users may clear localStorage by mistake. So anything that relies on localStorage is unreliable.

Okay, I understand. Thank you
