### ISSUE TITLE
(Asking for help)Add token counter

### ISSUE THREAD

**Issue by InterestingDarkness** [InterestingDarkness/ChatSydney#3]
Now I can't get tiktoken working in the browser, waiting for someone's help......

**Comment by xinerqu** [comment]
我刚刚安装了chatsydney,很好啊，没什么问题呀。虽然无法绕过微软的审查机制，但是bing本身，或者说sydney本身是没有任何限制和禁忌的。现在需要的是允许其他设备访问呢，这样就可以开放给没有梯子的小伙伴啦。

**Comment by InterestingDarkness** [comment]
For security reasons, I prefer not to allow other devices to connect in my code. You can always replace `localhost` in main.py with the local IP you want to serve on, or just `0.0.0.0`

**Comment by xinerqu** [comment]
thanks，Thank you very much, I understand. chatsydney is so cool.

**Comment by InterestingDarkness** [comment]
https://github.com/InterestingDarkness/ChatSydney/commit/90b018663579b64edef09ed73de0800aca259ed7
I've added a command line parameter to change listen port

**Comment by juzeon** [comment]
<https://github.com/wesmcouch/GPT-3-Encoder-browser/tree/no-fs-count-tokens>

这个项目好像可以直接在浏览器中调用。

**Comment by InterestingDarkness** [comment]
> https://github.com/wesmcouch/GPT-3-Encoder-browser/tree/no-fs-count-tokens
> 
> 这个项目好像可以直接在浏览器中调用。

没有cl100k词库

**Comment by InterestingDarkness** [comment]
```
import * as Tiktoken from 'https://cdn.skypack.dev/js-tiktoken?min'
const enc = Tiktoken.encodingForModel("gpt-4");
```
This works.
