### ISSUE TITLE
可以更新一下配置教程吗(Can you update the configuration tutorial?)

### ISSUE THREAD

**Issue by MaikuaiBlock** [InterestingDarkness/ChatSydney#30]
做的很棒,就是新版不会配置了,它不回应我(Great job, but the new version won't be configured, it won't respond to me)

**Comment by InterestingDarkness** [comment]
不回应是网络问题，main.py 有设置代理的命令行参数

**Comment by MaikuaiBlock** [comment]
但是以前的版本是可以回应我的

**Comment by InterestingDarkness** [comment]
用EdgeGPT 0.6.5

**Comment by MaikuaiBlock** [comment]
换了,还是没用,挂vpn都不行,把所有库都重装了一遍,也就只回第一句话,就不再回了,重开也没用

**Comment by InterestingDarkness** [comment]
should fixed in latest version
