### ISSUE TITLE
Looks like the user message has triggered the Bing filter

### ISSUE THREAD

**Issue by yagamilighttuski** [InterestingDarkness/ChatSydney#31]
请问作者这个问题怎么解决呢？下午用的时候还是好的，晚上用的时候出现了这个
![Snipaste_2023-05-27_20-59-54](https://github.com/InterestingDarkness/ChatSydney/assets/78994336/832dedb9-f50a-4ed7-9789-c3b43720b580)

**Comment by InterestingDarkness** [comment]
发全屏网页截图

**Comment by yagamilighttuski** [comment]
![QQ截图20230527212537](https://github.com/InterestingDarkness/ChatSydney/assets/78994336/5cb2dae7-32fd-4c59-98ce-ca6e796607a1)

**Comment by deeme** [comment]
这个还是要锁定版本，测试了可以EdgeGPT==0.6.5，再高就会显示触发过滤，低版本没测试

**Comment by InterestingDarkness** [comment]
不知道上游在搞什么，不懂“没坏就别修”吗

**Comment by deeme** [comment]
贴一个nginx.conf
`
		location /ws {
			proxy_pass http://localhost:65432/ws;
			proxy_http_version                 1.1;
			proxy_set_header Upgrade           $http_upgrade;
			proxy_set_header Connection        $connection_upgrade;
			proxy_set_header Host              $host;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_set_header X-Forwarded-Host  $host;
			proxy_set_header X-Forwarded-Port  $server_port;
		}

		location / {
			proxy_pass http://localhost:65432;
			proxy_set_header Host              $host;    
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_set_header X-Forwarded-Host  $host;
			proxy_set_header X-Forwarded-Port  $server_port;
		}
`
可以把html里面的ws换成wss

**Comment by yagamilighttuski** [comment]
> 这个还是要锁定版本，测试了可以EdgeGPT==0.6.5，再高就会显示触发过滤，低版本没测试

嗯嗯我之前用的0.6.6版本的 现在改成0.6.5已经不会触发过滤了 感谢感谢

**Comment by yagamilighttuski** [comment]
> 贴一个nginx.conf
> 
> ```
> 		location /ws {
> 			proxy_pass http://localhost:65432/ws;
> 			proxy_http_version                 1.1;
> 			proxy_set_header Upgrade           $http_upgrade;
> 			proxy_set_header Connection        $connection_upgrade;
> 			proxy_set_header Host              $host;
> 			proxy_set_header X-Forwarded-Proto $scheme;
> 			proxy_set_header X-Forwarded-Host  $host;
> 			proxy_set_header X-Forwarded-Port  $server_port;
> 		}
> 
> 		location / {
> 			proxy_pass http://localhost:65432;
> 			proxy_set_header Host              $host;    
> 			proxy_set_header X-Forwarded-Proto $scheme;
> 			proxy_set_header X-Forwarded-Host  $host;
> 			proxy_set_header X-Forwarded-Port  $server_port;
> 		}
> ```
> 可以把html里面的ws换成wss

这样修改后是可以支持更高版本的EdgeGPT吗？

**Comment by InterestingDarkness** [comment]
不能

**Comment by InterestingDarkness** [comment]
大部分时候不需要Nginx，main.py已经支持开放给其他人使用

**Comment by yagamilighttuski** [comment]
> 大部分时候不需要Nginx，main.py已经支持开放给其他人使用

了解了 十分感谢

**Comment by deeme** [comment]
> > 贴一个nginx.conf
> > ```
> > 		location /ws {
> > 			proxy_pass http://localhost:65432/ws;
> > 			proxy_http_version                 1.1;
> > 			proxy_set_header Upgrade           $http_upgrade;
> > 			proxy_set_header Connection        $connection_upgrade;
> > 			proxy_set_header Host              $host;
> > 			proxy_set_header X-Forwarded-Proto $scheme;
> > 			proxy_set_header X-Forwarded-Host  $host;
> > 			proxy_set_header X-Forwarded-Port  $server_port;
> > 		}
> > 
> > 		location / {
> > 			proxy_pass http://localhost:65432;
> > 			proxy_set_header Host              $host;    
> > 			proxy_set_header X-Forwarded-Proto $scheme;
> > 			proxy_set_header X-Forwarded-Host  $host;
> > 			proxy_set_header X-Forwarded-Port  $server_port;
> > 		}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以把html里面的ws换成wss
> 
> 这样修改后是可以支持更高版本的EdgeGPT吗？

不是，是部署到服务器绑定域名后https的访问没问题，要是ws的，好像浏览器默认不能以自定义域名的https访问，本地测试用ws，部署配置Nginx用wss，这是我遇到问题后解决的，不知道大伙的情况

**Comment by SAuP51** [comment]
> > 这个还是要锁定版本，测试了可以EdgeGPT==0.6.5，再高就会显示触发过滤，低版本没测试
> 
> 嗯嗯我之前用的0.6.6版本的 现在改成0.6.5已经不会触发过滤了 感谢感谢

我也遇到这个问题了 怎么改版本呀

**Comment by InterestingDarkness** [comment]
https://github.com/acheong08/EdgeGPT/pull/447
最新版应该已经没问题了

**Comment by yagamilighttuski** [comment]
> > > 这个还是要锁定版本，测试了可以EdgeGPT==0.6.5，再高就会显示触发过滤，低版本没测试
> > 
> > 嗯嗯我之前用的0.6.6版本的 现在改成0.6.5已经不会触发过滤了 感谢感谢
> 
> 我也遇到这个问题了 怎么改版本呀

pip install EdgeGPT==0.6.5

**Comment by MaikuaiBlock** [comment]
![QQ截图20230529220203](https://github.com/InterestingDarkness/ChatSydney/assets/110007324/29a4c5bd-ee7d-44ae-a1a6-57c721ed2832)
那这样呢

**Comment by yagamilighttuski** [comment]
> ![QQ截图20230529220203](https://github.com/InterestingDarkness/ChatSydney/assets/110007324/29a4c5bd-ee7d-44ae-a1a6-57c721ed2832)
> 那这样呢用的版本是0.6.5

我也开始有这个问题了

**Comment by InterestingDarkness** [comment]
如果不能用请开启翻墙并设置 `main.py --proxy http://127.0.0.1:7890` 启动参数，7890替换成你的本地代理端口

**Comment by MaikuaiBlock** [comment]
![QQ截图20230529233201](https://github.com/InterestingDarkness/ChatSydney/assets/110007324/2c7e49c1-89e3-4cac-8ffd-e4f6f6890caa)

**Comment by InterestingDarkness** [comment]
从这个错误信息，我什么都看不到，如果不用EdgeGPT，我或许能一眼看出问题在哪里

**Comment by gunshipwu** [comment]
> main.py --proxy http://127.0.0.1:7890

请问，这个在哪里设？

**Comment by InterestingDarkness** [comment]
但正如About上写的，Seeking a new maintainer.
Sydney我现在自己都不用，自然无心继续做Sydney相关开发

**Comment by InterestingDarkness** [comment]
> > main.py --proxy http://127.0.0.1:7890
> 
> 请问，这个在哪里设？

命令提示符运行 `python main.py --proxy http://127.0.0.1:7890/`

**Comment by MaikuaiBlock** [comment]
ok行吧我自己再看看

**Comment by gunshipwu** [comment]
> > > main.py --proxy http://127.0.0.1:7890
> > 
> > 
> > 请问，这个在哪里设？
> 
> 命令提示符运行 `python main.py --proxy http://127.0.0.1:7890/`

搞定，谢谢大佬。

**Comment by MaikuaiBlock** [comment]
可为什么以前的版本用起来很顺利

**Comment by InterestingDarkness** [comment]
那请降级到能用的版本，这里不是EdgeGPT项目

**Comment by gunshipwu** [comment]
> > > main.py --proxy http://127.0.0.1:7890
> > 
> > 
> > 请问，这个在哪里设？
> 
> 命令提示符运行 `python main.py --proxy http://127.0.0.1:7890`

SydneyQt-master 搞定了，main.py 里直接改proxy=XXXXXXXXXXX就好了，

但您的ChatSydney-react 的main.py  里搜不到proxy


按您说的在提示行下似乎报格式错误 

PS D:\ChatSydney-react> python main.py --proxy http://127.0.0.1:7890
usage: main.py [-h] [--host HOST]
main.py: error: unrecognized arguments: --proxy http://127.0.0.1:7890
PS D:\ChatSydney-react>

感觉应该是最新的WINDOWS 更新 让这个项目不能从系统的常量中提取翻墙的端口了....大概昨天睡觉前我更新了WIN推送的更新。。

**Comment by xiaoBingge114514** [comment]
![image](https://github.com/InterestingDarkness/ChatSydney/assets/105868119/5c789bdf-92b9-439d-b0d9-9c1141eb6d27)
我下新的用了之后也出问题了，0.4.4和0.6.5还有0.6.10都报错这个，给我整不会了TTOTT

**Comment by InterestingDarkness** [comment]
> > > > main.py --proxy http://127.0.0.1:7890
> > > 
> > > 
> > > 请问，这个在哪里设？
> > 
> > 
> > 命令提示符运行 `python main.py --proxy http://127.0.0.1:7890`
> 
> SydneyQt-master 搞定了，main.py 里直接改把proxy = self.config.get('proxy') 改成具体的http://127.0.0.1:7890 就好了。
> 
> 但您的ChatSydney-react 的main.py 里搜不到proxy
> 
> 按您说的在提示行下似乎报格式错误
> 
> PS D:\ChatSydney-react> python main.py --proxy http://127.0.0.1:10809 usage: main.py [-h] [--host HOST] main.py: error: unrecognized arguments: --proxy http://127.0.0.1:10809 PS D:\ChatSydney-react>
> 
> 感觉应该是最新的WINDOWS 更新 让这个项目不能从系统的常量中提取翻墙的端口了....大概昨天睡觉前我更新了WIN推送的更新。。大概就是self.config.get('proxy') 失效了。

用最新的ChatSydney

**Comment by InterestingDarkness** [comment]
> ![image](https://user-images.githubusercontent.com/105868119/241829995-5c789bdf-92b9-439d-b0d9-9c1141eb6d27.png) 我下新的用了之后也出问题了，0.4.4和0.6.5还有0.6.10都报错这个，给我整不会了TTOTT

代理设置了吗？

**Comment by SAuP51** [comment]
> 但正如About上写的，Seeking a new maintainer. Sydney我现在自己都不用，自然无心继续做Sydney相关开发

那大佬现在用什么 紧跟大佬的步伐

**Comment by InterestingDarkness** [comment]
> 那大佬现在用什么 紧跟大佬的步伐

我不是大佬
我现在用ChatGPT Plus

**Comment by SAuP51** [comment]
> > 那大佬现在用什么 紧跟大佬的步伐
> 
> 我不是大佬 我现在用ChatGPT Plus


> 

莫谦虚 是大佬 还是有几把刷子的 哈哈哈 plus不够用感觉

**Comment by InterestingDarkness** [comment]
Fixed by embedding a specific EdgeGPT version
