### ISSUE TITLE
无魔法不能使用

### ISSUE THREAD

**Issue by renqabs** [InterestingDarkness/ChatSydney#32]
是不是现在必须使用魔法才可以，昨天还好好的，我刚试了下，用了魔法才能正常回复

**Comment by InterestingDarkness** [comment]
只保证非中国IP都能用，EdgeGPT在中国使用第三方反向代理，不保证可用性

**Comment by InterestingDarkness** [comment]
而且第三方反向代理不代理 sydney.bing.com ，如果你的网络环境无法访问 sydney.bing.com 也是无法使用的

**Comment by renqabs** [comment]
好的，十分感谢

**Comment by renqabs** [comment]
今天又可以了，不用魔法也行了。。。
