### ISSUE TITLE
使用edgegpt 0.6.5以上版本不显示Suggestions，edgegpt 0.6.5正常显示Suggestions

### ISSUE THREAD

**Issue by renqabs** [InterestingDarkness/ChatSydney#34]

**Comment by InterestingDarkness** [comment]
https://github.com/viopsa233/AI-testers-Forum/discussions/69

**Comment by InterestingDarkness** [comment]
https://github.com/InterestingDarkness/ChatSydney/commit/24db58eea4651de6d5227a1465ec707c85dc1df5
问题已解决，但我不推荐用0.6.5之后的版本

**Comment by renqabs** [comment]
收到，十分感谢
