### ISSUE TITLE
是否可以加一个消息被回收自动发送“从你的上一句继续”的功能

### ISSUE THREAD

**Issue by 948199363** [InterestingDarkness/ChatSydney#35]
因为大部分情况下，遇到这个报错都是会直接点继续的，是否可以加个开关让程序自动点，这样避免生成的时候一直中断要手动处理

**Comment by InterestingDarkness** [comment]
Completed https://github.com/InterestingDarkness/ChatSydney/commit/425fcf69346006f21daa9b016d96f9749b7f40a7
