### ISSUE TITLE
Continue on revoke 的bug

### ISSUE THREAD

**Issue by 948199363** [InterestingDarkness/ChatSydney#36]
revoke那个特性大佬加的好快！好评！不过好像有个bug，在revoke之后自动发消息的时候，被revoke的那段文案似乎没有加进上下文，导致续写的不是被revoke的那段文案，而是那段文案的前一条文案 —— 也就是续写出的内容实际上跟被revoke的文案是相似的，这样就很容易一直循环这条被revoke的文案。

**Comment by InterestingDarkness** [comment]
fixed https://github.com/InterestingDarkness/ChatSydney/commit/569763190806c965d977237e5850c1ffc510c461
