### ISSUE TITLE
使用EdgeGPT 0.7.2时回复变成空白的问题

### ISSUE THREAD

**Issue by renqabs** [InterestingDarkness/ChatSydney#37]
应该是index.html 419行const message = response.item.messages[response.item.messages.length - 1]的问题，
改为const message = response.item.messages[response.item.messages.length - 2]
暂时可以解决问题，已提交PR
![搜狗截图20230603135739](https://github.com/InterestingDarkness/ChatSydney/assets/130155002/c76b3b37-d7cc-467d-938f-749d937e9c97)

**Comment by InterestingDarkness** [comment]
https://github.com/viopsa233/AI-testers-Forum/discussions/69
这里的代码是为了适配当时的新版EdgeGPT加上的，现在出问题了。只推荐EdgeGPT 0.6.5，如果这样修改旧版EdgeGPT的用户会出问题。下载 https://github.com/acheong08/EdgeGPT/blob/0.6.5/src/EdgeGPT.py 到ChatSydney目录来锁定ChatSydney使用的EdgeGPT版本。

**Comment by renqabs** [comment]
我提交了一个PR，我在Edge 0.6.5版本下也测试了下，暂时没发现什么问题，不过我尊重你的选择

**Comment by InterestingDarkness** [comment]
不一定总在-2位置，如果做判断比较复杂，我内置了一个最新的改版EdgeGPT

**Comment by renqabs** [comment]
好的，十分感谢
