### ISSUE TITLE
Do not show Claude message

### ISSUE THREAD

**Issue by viopsa233** [InterestingDarkness/ChatSydney#52]
slack发送了消息,但是chatSydney没有显示消息?
![网页捕获_16-6-2023_201229_app slack com](https://github.com/InterestingDarkness/ChatSydney/assets/118115208/d86a5cbc-b8b4-4ab3-96e5-6b1992a94259)
![网页捕获_16-6-2023_201239_localhost](https://github.com/InterestingDarkness/ChatSydney/assets/118115208/7173fb8e-7439-409a-81b5-b93a4f4fcda3)

**Comment by viopsa233** [comment]
再问一下claude.json中的`slackChannelId`是什么,是频道ID吗?

**Comment by InterestingDarkness** [comment]
> 再问一下claude.json中的`slackChannelId`是什么,是频道ID吗?

是

**Comment by viopsa233** [comment]
我去,搞清楚了,在公开频道才行🤣
